# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 11:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pitanja', '0073_auto_20170921_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prostornipodaci',
            name='Odrediti_vazne_podatke_od_drugih_organizacija_za_redovne_aktivnosti',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pitanja.Pitanje3_4', unique=True),
        ),
        migrations.AlterField(
            model_name='prostornipodaci',
            name='Uneti_podatke_o_podacima_koje_vasa_organizacija_proizvodi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pitanja.Pitanje3_2', unique=True),
        ),
        migrations.AlterField(
            model_name='prostornipodaci',
            name='Za_koje_od_navedenih_INSPIRE_tema_proizvodite_podatke',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pitanja.Pitanje3_1', unique=True),
        ),
        migrations.AlterField(
            model_name='standardizacijaotvorenihpodataka',
            name='Koliko_se_slazete_sa_tvrdnjama',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pitanja.Pitanje5_14', unique=True),
        ),
        migrations.AlterField(
            model_name='standardizacijaotvorenihpodataka',
            name='Prepreke_za_uspostavljanje_koncepta_gopodataka',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pitanja.Pitanje5_12', unique=True),
        ),
        migrations.AlterField(
            model_name='standardizacijaotvorenihpodataka',
            name='Propis_prava_koriscenja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pitanja.Pitanje5_4', unique=True),
        ),
        migrations.AlterField(
            model_name='standardizacijaotvorenihpodataka',
            name='Status_standarda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pitanja.Pitanje5_1', unique=True),
        ),
        migrations.AlterField(
            model_name='standardizacijaotvorenihpodataka',
            name='Vaznost_Prepreka',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pitanja.Pitanje5_13', unique=True),
        ),
    ]
