# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 12:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pitanja', '0074_auto_20170922_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kadroviinfrastruktura',
            name='Koje_aplikacije_su_u_upotrebi_za_obradu',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='pitanja.Pitanje2_5', unique=True),
        ),
        migrations.AlterField(
            model_name='kadroviinfrastruktura',
            name='Koji_sistemi_za_upravljanje_bazama_imate',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='pitanja.Pitanje2_6', unique=True),
        ),
        migrations.AlterField(
            model_name='kadroviinfrastruktura',
            name='Mobilne_gis_aplikacije',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='pitanja.Pitanje2_8', unique=True),
        ),
        migrations.AlterField(
            model_name='prostornipodaci',
            name='Koje_prostorne_podatke_nabavljate_od_drugih',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pitanja.Pitanje3_3', unique=True),
        ),
        migrations.AlterField(
            model_name='prostornipodaci',
            name='Za_kojim_prostornim_podacima_imate_potrebu_a_koji_nisu_dostupni',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pitanja.Pitanje3_5', unique=True),
        ),
        migrations.AlterField(
            model_name='standardizacijaotvorenihpodataka',
            name='Standardi_iz_oblasti_geoinformacija',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pitanja.Pitanje5_2', unique=True),
        ),
    ]
