# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitanja', '0076_organizacijaosnovnipodaci_jedinstveni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitanje3_2',
            name='Dostupnost',
            field=models.CharField(choices=[('Интерно', 'Интерно'), ('Доступно свима', 'Доступно свима')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='pitanje3_2',
            name='Prava_Pristupa',
            field=models.CharField(choices=[('Интерно', 'Интерно'), ('Доступно свима', 'Доступно свима')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='pitanje3_2',
            name='Web_Servis',
            field=models.CharField(choices=[('Интерно', 'Интерно'), ('Доступно свима', 'Доступно свима')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='saradnjaizmedjusubjekata',
            name='Da_li_Podrzavate_razmenu_podataka_preko_portala_e_placanje',
            field=models.CharField(blank=True, choices=[('Да, подржавамо', 'Да, подржавамо'), ('Не, не подржавамо', 'Не, не подржавамо')], max_length=100, null=True),
        ),
    ]
