# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 08:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pitanja', '0079_auto_20171023_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pitanje2_5',
            name='Program',
        ),
        migrations.RemoveField(
            model_name='pitanje2_5',
            name='Ucestalost_Koriscenja',
        ),
    ]
