# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitanja', '0080_auto_20171024_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitanje2_5',
            name='Program',
            field=models.CharField(choices=[('ArcGIS Desktop (ESRI)', 'ArcGIS Desktop (ESRI)'), ('Q GIS', 'Q GIS'), ('MapInfo', 'MapInfo'), ('GeoMedia', 'GeoMedia'), ('MapSoft', 'MapSoft'), ('AutoCAD', 'AutoCAD'), ('Bently MicroStation', 'Bently MicroStation'), ('ERDAS IMAGINE', 'ERDAS IMAGINE'), ('Leica Photogrametry Suite', 'Leica Photogrametry Suite'), ('eCognition Trimble', 'eCognition Trimble'), ('Интерно креиране апликације', 'Интерно креиране апликације'), ('Остало', 'Остало')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pitanje2_5',
            name='Ucestalost_Koriscenja',
            field=models.CharField(choices=[('Свакодневно', 'Свакодневно'), ('Често за обимније анализе', 'Често за обимније анализе'), ('Понекад за посебне анализе и извештаје', 'Понекад за посебне анализе и извештаје')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pitanje3_2',
            name='Dostupnost',
            field=models.CharField(choices=[('интерноо', 'Интерно'), ('доступно свима', 'Доступно свима')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='pitanje3_2',
            name='Prava_Pristupa',
            field=models.CharField(choices=[('интерноо', 'Интерно'), ('доступно свима', 'Доступно свима')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='pitanje3_2',
            name='Web_Servis',
            field=models.CharField(choices=[('интерноо', 'Интерно'), ('доступно свима', 'Доступно свима')], max_length=1000),
        ),
    ]
