# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-25 09:15
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pitanja', '0087_auto_20171024_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitanje2_5',
            name='Namena_ostalo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Namena_ostalo '),
        ),
        migrations.AddField(
            model_name='pitanje2_5',
            name='Program_ostalo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Program_ostalo'),
        ),
        migrations.AddField(
            model_name='pitanje2_6',
            name='Namena_ostalo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Namena_ostalo '),
        ),
        migrations.AddField(
            model_name='pitanje2_6',
            name='Program_ostalo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Program_ostalo'),
        ),
        migrations.AddField(
            model_name='pitanje2_8',
            name='Namena_ostalo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Namena_ostalo '),
        ),
        migrations.AddField(
            model_name='pitanje2_8',
            name='Program_ostalo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Program_ostalo'),
        ),
        migrations.AddField(
            model_name='pitanje3_3',
            name='Proizvod_ostalo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Proizvod_ostalo'),
        ),
        migrations.AddField(
            model_name='pitanje3_3',
            name='Proizvodjac_ostalo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Proizvodjac_ostalo'),
        ),
        migrations.AddField(
            model_name='pitanje3_3',
            name='Prostorni_Obuhvat_ostalo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Prostorni_Obuhvat_ostalo'),
        ),
        migrations.AddField(
            model_name='pitanje3_5',
            name='Proizvod_ostalo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Proizvod_ostalo'),
        ),
        migrations.AddField(
            model_name='pitanje3_5',
            name='Proizvodjac_ostalo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Proizvodjac_ostalo'),
        ),
        migrations.AddField(
            model_name='pitanje3_5',
            name='Prostorni_obuhvat_ostalo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Prostorni_obuhvat_ostalo'),
        ),
        migrations.AddField(
            model_name='pitanje3_5',
            name='Razlog_nedostupnosti_ostalo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Razlog_nedostupnosti_ostalo'),
        ),
        migrations.AlterField(
            model_name='organizacijaosnovnipodaci',
            name='Adresa',
            field=models.CharField(help_text='Место, Улица и број: (нпр. Београд, Ресавска 25)', max_length=50, verbose_name='Адреса'),
        ),
        migrations.AlterField(
            model_name='organizacijaosnovnipodaci',
            name='E_mail',
            field=models.EmailField(help_text='нпр. primer@mail.com', max_length=254, verbose_name='Е-адреса'),
        ),
        migrations.AlterField(
            model_name='organizacijaosnovnipodaci',
            name='E_mail_kontakt_osobe',
            field=models.EmailField(help_text='нпр. primer@mail.com', max_length=254, verbose_name='Е-адреса'),
        ),
        migrations.AlterField(
            model_name='organizacijaosnovnipodaci',
            name='Internet_sajt',
            field=models.URLField(help_text='Линк ка сајту: (нпр. www.rgz.gov.rs)', verbose_name='Интернет сајт'),
        ),
        migrations.AlterField(
            model_name='pitanje2_5',
            name='Namena',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('******', '******'), ('Израда планова и карата', 'Израда планова и карата'), ('Пројектовање', 'Пројектовање'), ('Извештавање', 'Извештавање'), ('Управљање и планирање коришћења земљишта', 'Управљање и планирање коришћења земљишта'), ('Урбанизам и грађевински послови', 'Урбанизам и грађевински послови'), ('Праћење промена и просторне анализе', 'Праћење промена и просторне анализе'), ('Креирање и анализа ДМТ', 'Креирање и анализа ДМТ'), ('Геореференцирање и обрада растерских података', 'Геореференцирање и обрада растерских података'), ('Даљинска детекција', 'Даљинска детекција'), ('Обрада података добијених ласерским скенирањем', 'Обрада података добијених ласерским скенирањем'), ('Остало', 'Остало')], max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='pitanje2_5',
            name='Program',
            field=models.CharField(choices=[('Не користимо ову врсту апликације', 'Не користимо ову врсту апликације'), ('ArcGIS Desktop (ESRI)', 'ArcGIS Desktop (ESRI)'), ('Q GIS', 'Q GIS'), ('MapInfo', 'MapInfo'), ('GeoMedia', 'GeoMedia'), ('MapSoft', 'MapSoft'), ('AutoCAD', 'AutoCAD'), ('Bently MicroStation', 'Bently MicroStation'), ('ERDAS IMAGINE', 'ERDAS IMAGINE'), ('Leica Photogrametry Suite', 'Leica Photogrametry Suite'), ('eCognition Trimble', 'eCognition Trimble'), ('Интерно креиране апликације', 'Интерно креиране апликације'), ('Остало', 'Остало')], max_length=100),
        ),
        migrations.AlterField(
            model_name='pitanje2_5',
            name='Ucestalost_Koriscenja',
            field=models.CharField(choices=[('******', '******'), ('Свакодневно', 'Свакодневно'), ('Често за обимније анализе', 'Често за обимније анализе'), ('Понекад за посебне анализе и извештаје', 'Понекад за посебне анализе и извештаје')], max_length=100),
        ),
        migrations.AlterField(
            model_name='pitanje2_6',
            name='Namena',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('******', '******'), ('Складиштење просторних података', 'Складиштење просторних података'), ('Складиштење алфанумеричких података', 'Складиштење алфанумеричких података'), ('Остало', 'Остало')], max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='pitanje2_6',
            name='Program',
            field=models.CharField(choices=[('Не користимо ову врсту апликације', 'Не користимо ову врсту апликације'), ('MS Access', 'MS Access'), ('Oracle ', 'Oracle '), ('PostgreSQL', 'PostgreSQL'), ('MicrosoftSQL', 'MicrosoftSQL'), ('Остало', 'Остало')], max_length=100),
        ),
        migrations.AlterField(
            model_name='pitanje2_8',
            name='Namena',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('******', '******'), ('Прикупљање података са терена', 'Прикупљање података са терена'), ('Праћење возила', 'Праћење возила'), ('Остало', 'Остало')], max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='pitanje2_8',
            name='Program',
            field=models.CharField(choices=[('Не користимо ову врсту апликације', 'Не користимо ову врсту апликације'), ('ArcPAD', 'ArcPAD'), ('Leica Zeno', 'Leica Zeno'), ('Интерно креиране апликације', 'Интерно креиране апликације'), ('Остало', 'Остало')], max_length=100),
        ),
        migrations.AlterField(
            model_name='pitanje3_2',
            name='Format_Distribucije',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Adobe PDF', 'Adobe PDF (*.pdf)'), ('ASCII gridded', 'ASCII gridded data format (*.xyz)'), ('GeoTIFF', 'GeoTIFF (*.tif)'), ('TIFF', 'TIFF (*.tif)'), ('GML', 'GML (*.gml)'), ('CorelDraw', 'CorelDraw file format (*.cdr)'), ('TIFF', 'TIFF (*.tif), TFW (*.tfw)'), ('ECW', 'ECW Image file format (*.ecw)'), ('MrSID', 'MrSID file format (*.sid)'), ('ESRI', 'ESRI shapefile (*.shp)'), ('MapInfo ', 'MapInfo TAB format (*.tab)'), ('KML', 'KML file format (*.kml, *.kmz)'), ('IMG ', 'IMG file format (*.img)'), ('NTF', 'NTF Image file format (*.ntf)'), ('AutoCAD DXF', 'AutoCAD DXF (*.dxf)'), ('ESRI file', 'ESRI file geodatabase (*.gdb)'), ('ESRI personal', 'ESRI personal geodatabase (*.mdb)'), ('JPG', 'JPG file format (*.jpg)'), ('Microsoft Excel', 'Microsoft Excel file format (*.xls)'), ('Остало', 'Остало')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='pitanje3_3',
            name='Proizvod',
            field=models.CharField(choices=[('*****************************', '*****************************'), ('Катастарске парцеле и објекти', 'Катастарске парцеле и објекти'), ('Подаци катастра непокретности', 'Подаци катастра непокретности'), ('Ортофото', 'Ортофото'), ('Адресе', 'Адресе'), ('Топографске карте', 'Топографске карте (1:20 000 и ситније размере)'), ('Основна државна карта', 'Основна државна карта (1:5000; 1:10 000)'), ('Просторни планови', 'Просторни планови'), ('Друго', 'Друго')], max_length=100),
        ),
        migrations.AlterField(
            model_name='pitanje3_3',
            name='Proizvodjac',
            field=models.CharField(choices=[('Не користимо ову врсту апликације', 'Не користимо ову врсту апликације'), ('РГЗ', 'Републички геодетски завод'), ('ВГИ', 'Војногеографски институт'), ('Завод за заштиту природе Србије', 'Завод за заштиту природе Србије'), ('Републички завод за статистику', 'Републички завод за статистику'), ('Републичка дирекција за воде', 'Републичка дирекција за воде'), ('Републички хидрометролошки завод', 'Републички хидрометролошки завод'), ('Завод за заштиту споменика културе', 'Завод за заштиту споменика културе'), ('ЈП Пошта Србије', 'ЈП Пошта Србије'), ('ЈП Путеви Србије', 'ЈП Путеви Србије'), ('European Environment Agency', 'European Environment Agency (EEA)'), ('Друго', 'Друго')], max_length=100),
        ),
        migrations.AlterField(
            model_name='pitanje3_3',
            name='Prostorni_Obuhvat',
            field=models.CharField(choices=[('***************************', '***************************'), ('Територија Републике Србије', 'Територија Републике Србије'), ('Територија административне надлежности организације', 'Територија административне надлежности организације'), ('Друго', 'Друго')], max_length=100),
        ),
        migrations.AlterField(
            model_name='pitanje3_5',
            name='Proizvod',
            field=models.CharField(choices=[('*****************************', '*****************************'), ('Катастарске парцеле и објекти', 'Катастарске парцеле и објекти'), ('Подаци катастра непокретности', 'Подаци катастра непокретности'), ('Ортофото', 'Ортофото'), ('Адресе', 'Адресе'), ('Топографске карте ', 'Топографске карте (1:20 000 и ситније размере)'), ('Основна државна карта', 'Основна државна карта (1:5000; 1:10 000)'), ('Просторни планови', 'Просторни планови'), ('Друго', 'Друго')], max_length=100),
        ),
        migrations.AlterField(
            model_name='pitanje3_5',
            name='Proizvodjac',
            field=models.CharField(choices=[('*****************************', '*****************************'), ('РГЗ', 'Републички геодетски завод'), ('ВГИ', 'Војногеографски институт'), ('Завод за заштиту природе Србије', 'Завод за заштиту природе Србије'), ('Републички завод за статистику', 'Републички завод за статистику'), ('Републичка дирекција за воде', 'Републичка дирекција за воде'), ('Републички хидрометролошки завод', 'Републички хидрометролошки завод'), ('Завод за заштиту споменика културе', 'Завод за заштиту споменика културе'), ('ЈП Пошта Србије', 'ЈП Пошта Србије'), ('ЈП Путеви Србије', 'ЈП Путеви Србије'), ('European Environment Agency', 'European Environment Agency (EEA)'), ('Друго', 'Друго')], max_length=100),
        ),
        migrations.AlterField(
            model_name='pitanje3_5',
            name='Prostorni_obuhvat',
            field=models.CharField(choices=[('*****************************', '*****************************'), ('Територија Републике Србије', 'Територија Републике Србије'), ('Територија административне надлежности организације', 'Територија административне надлежности организације'), ('Друго', 'Друго')], max_length=100),
        ),
        migrations.AlterField(
            model_name='pitanje3_5',
            name='Razlog_nedostupnosti',
            field=models.CharField(choices=[('*****************************', '*****************************'), ('Цена', 'Цена'), ('Непостојање', 'Непостојање'), ('Неажурност', 'Неажурност'), ('Недоступност на интернету', 'Недоступност на интернету'), ('Начин преузимања', 'Начин преузимања'), ('Непокривеност', 'Непокривеност'), ('Непостојање дигиталне форме', 'Непостојање дигиталне форме'), ('Лоша садрадња са надлежном организацијом', 'Лоша садрадња са надлежном организацијом'), ('Тајност података', 'Тајност података'), ('Друго', 'Друго')], max_length=100),
        ),
        migrations.AlterField(
            model_name='saradnjaizmedjusubjekata',
            name='Ko_su_korisnici_vasih_proizvoda',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Сопствене потребе', 'Сопствене потребе'), ('Органи државне управе', 'Органи државне управе'), ('Органи територијалне аутономије', 'Органи територијалне аутономије'), ('Органи локалне самоуправе', 'Органи локалне самоуправе'), ('Јавне агенције', 'Јавне агенције'), ('Јавна предузећа', 'Јавна предузећа'), ('Научно-образовне установе', 'Научно-образовне установе'), ('Пројектантскo-урбанистичке организације', 'Пројектантскo-урбанистичке организације'), ('Приватне организације', 'Приватне организације'), ('Европске и друге међународне институције', 'Европске и друге међународне институције'), ('Грађани', 'Грађани'), ('Друго', 'Друго')], max_length=300),
        ),
        migrations.AlterField(
            model_name='sekcija2_5_namena_choicesclass',
            name='namena_choices',
            field=models.CharField(choices=[('******', '******'), ('Израда планова и карата', 'Израда планова и карата'), ('Пројектовање', 'Пројектовање'), ('Извештавање', 'Извештавање'), ('Управљање и планирање коришћења земљишта', 'Управљање и планирање коришћења земљишта'), ('Урбанизам и грађевински послови', 'Урбанизам и грађевински послови'), ('Праћење промена и просторне анализе', 'Праћење промена и просторне анализе'), ('Креирање и анализа ДМТ', 'Креирање и анализа ДМТ'), ('Геореференцирање и обрада растерских података', 'Геореференцирање и обрада растерских података'), ('Даљинска детекција', 'Даљинска детекција'), ('Обрада података добијених ласерским скенирањем', 'Обрада података добијених ласерским скенирањем'), ('Остало', 'Остало')], max_length=100),
        ),
    ]
